kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com 
volumeBindingMode: WaitForFirstConsumer #bir pod olustur bağla denildiğinde bağlanıyor. ebs ten boşuna volume oluşturmamıs oluyor
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1 #düşük perfermanslı volune tipi
  iopsPerGB: "50"
  encrypted: "true"
allowedTopologies:  # subneti kısıtladığım için bana ordan volume ayır. us-east-1a da olusturacak volume.
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1a